### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by pineapple954** [DominikFilipiak/KGTN-ens#2]
I tried to run this project, but it was not successful. The readme was not detailed enough. Can you analyze more details? The current difficulty I am facing is not knowing which dataset to use and where to place the dataset. Can you tell me? Thank you

**Comment by DominikFilipiak** [comment]
Hello, have you tried to follow [this section of the KGTN README](https://github.com/MyChocer/KGTN/blob/master/README.md#running-the-code)? If so, could you tell me which points exactly are failing for you?

**Comment by pineapple954** [comment]
I have read the readme you mentioned, but I still have some doubts. Is the dataset you are using ‘kaggle competitions download - c imagenet object localization challenge’, and what are the file directories that need to be changed. Can I use higher versions of Torch and Cuda. thanks

**Comment by DominikFilipiak** [comment]
> Is the dataset you are using ‘kaggle competitions download - c imagenet object localization challenge’, and what are the file directories that need to be changed. 

It's the standard ImageNet. The paths are in `DataSplit/FeatureExtractor/*.yaml` files under `dataset_params.rootdir`.

> Can I use higher versions of Torch and Cuda. thanks

I recommend the ones mentioned, the other ones has not been tested. You might be interested in running the mentioned docker image.

Hope this helps.

**Comment by pineapple954** [comment]
![~_3USTFY%ZNSS LP DGRA6T](https://github.com/DominikFilipiak/KGTN-ens/assets/95961113/dcb3e48b-ea02-468d-be84-d4d4fdd5509a)
thanks for your reply. In this notebook, I see that you are using this dataset instead of the standard version of Imagenet(2012). If you are using the standard version of the dataset, can you share the download link

**Comment by DominikFilipiak** [comment]
In principle, that's the standard link: https://www.image-net.org

The notebook you referring to shows the kaggle subset which should be equivalent for our purpose (don't remember it now, sorry). 

It should not be in this folder as well (shall be in `notebooks/`). I'll try to clean up the repository when I'll find some time.

**Comment by pineapple954** [comment]
thanks for you reply！Can you tell me how to convert a knowledge graph ttl file into an npy file? I want to convert a YAGO knowledge graph into an npy file.thanks!

**Comment by DominikFilipiak** [comment]
You can e.g. create knowledge graph embeddings (I used the ones from PyTorch-BigGraph, see `notebooks/1_pretrained_wikidata_embeddings_check.ipynb`) and then calculate distances between them (like in `notebooks/3_create_adjacency_matrices.ipynb`).

**Comment by pineapple954** [comment]
I have carefully read your Notebook and tried several times to generate an embedded NPY file, but I still failed. Can you provide a more detailed process? Thank you
