### ISSUE TITLE
questions about embedding

### ISSUE THREAD

**Issue by pineapple954** [DominikFilipiak/KGTN-ens#3]
May I ask if the knowledge alignment in the wiki knowledge graph embedding you have built includes new classes and base classes, or only new classes

**Comment by DominikFilipiak** [comment]
New and base. See the details in the paper:
> We used the pre-trained 200-dimensional embeddings of Wikidata entities from PyTorch BigGraph [18], which are publicly available2 . The embeddings were prepared using the full Wikidata dump from 2019-03-06. All but three entities were directly mapped to embeddings to their Wikidata ID. Three entities (Q1295201, Q98957255, Q89579852) could not be instantly matched – they were manually matched to "grocery store"@en, "cricket"@en, and Q655301 respectively. Having the mapping, now we create an embedding array, ordered as the mappings in the original KGTN paper **(that is, as a 1000 × 200 array, where 200 denotes the dimensionality of a single embedding)**. The same function from (18) was used to generate final correla- tions between the embeddings, although this time λ = 0.32 was used (see Section 4.3).
